version: 2
jobs:
    bob:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "A first hello"
    john:
        docker:
             - image: circleci/ruby:2.4.1
        steps:
             - checkout
            - run: echo "Double Trouble"
workflows:
    version: 2
    bob_john:
        jobs:
            - bob
            - john
